---
wownero_remote_url: 'https://git.wownero.com/attachments/ff0be4f5-37b6-4208-aee3-0ca4c8e97c89'
wownero_remote_hash: 'sha256:709b905cf853035b1e1660f9de54be44ef4fcfef3924489bff38dc090866ff58'
wownero_version: "0.9.2.2"
wownero_bin_dir: "/usr/local/bin"
wownerod_path: "{{ wownero_bin_dir }}/wownerod"
wownerod_p2p_port: "34567"
wownerod_rpc_port: "34568"
